services:
  # Backend API Service
  - type: web
    name: smart-shop-api
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    numInstances: 1
    scaling:
      minInstances: 1
      maxInstances: 1
    envVars:
      - key: PORT
        value: 10000
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: "-Xms256m -Xmx512m"

databases:
  - name: smart-shop-db
    plan: starter
    databaseName: smartshop
    user: smartshop 