services:
  # A web service
  - type: web
    name: smartshop-api
    env: docker
    plan: free
    buildCommand: ./build.sh
    startCommand: ./start.sh
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 10000
      - key: APP_URL
        value: https://smartshop-api.onrender.com
      - key: AIVEN_DB_HOST
        value: smartshop-sandeep-e8db.h.aivencloud.com
      - key: AIVEN_DB_PORT
        value: "24114"
      - key: AIVEN_DB_NAME
        value: defaultdb
      - key: AIVEN_DB_USERNAME
        value: avnadmin
      - key: AIVEN_DB_PASSWORD
        value: AVNS_ZhDZPpZQMeC6uyk9TnV
      - key: JWT_SECRET
        generateValue: true
      - key: TZ
        value: UTC

# No need for database definition since we're using Aiven
# databases:
#   - name: smart-shop-db
#     plan: free
#     databaseName: smart_shop
#     ipAllowList: [] 