services:
  # A web service
  - type: web
    name: smartshop-api
    env: docker
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: smart-shop-db
    plan: free
    databaseName: smart_shop
    ipAllowList: [] 