services:
  # Backend API Service
  - type: web
    name: smart-shop-api
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    numInstances: 1
    scaling:
      minInstances: 1
      maxInstances: 1
    envVars:
      - key: DB_HOST
        value: smartshop-sandeep-e8db.h.aivencloud.com
      - key: DB_PORT
        value: 24114
      - key: DB_NAME
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        value: AVNS_ZhDZPpZQMeC6uyk9TnV
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 8080
      - key: SPRING_CONFIG_USE_LEGACY_PROCESSING
        value: true
      - key: JAVA_OPTS
        value: "-Xms256m -Xmx512m"

databases:
  - name: smart-shop-db
    plan: starter
    databaseName: smartshop
    user: smartshop 